# -*- coding: utf-8 -*-
"""ML(labsheet5).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/193Su2aHD49U-hKaDsxhHiWKoEvBWMIDF
"""

!pip install pandas seaborn matplotlib

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#Load Dataset
df = pd.read_csv("/content/sample_data/california_housing_train.csv")

#Display First 5 Rows
df.head()

#Check Dataset Shape
df.shape

#Display Column Names
df.columns

#Check Data Types
df.dtypes

#Check Missing Values
df.isnull().sum()

# 1 Univariate Analysis
# Histogram of Numerical Column
sns.histplot(df["housing_median_age"])

plt.show()

#Histogram with KDE
sns.histplot(df["housing_median_age"], kde=True)

plt.show()

#Identify Skewness
df["housing_median_age"].skew()

#Count Plot for Categorical Column
sns.countplot(x="housing_median_age", data=df)

plt.show()

#Change Color Palette
sns.set_palette("Set2")

sns.countplot(x="housing_median_age", data=df)

plt.show()

#Rotate Axis Labels
plt.xticks(rotation=45)

sns.countplot(x="housing_median_age", data=df)

plt.show()

#Identify Outliers
sns.boxplot(x=df["housing_median_age"])

plt.show()

#Save Plot
sns.histplot(df["housing_median_age"], kde=True)

plt.savefig("univariate_plot.png")

plt.show()

#2. Bivariate Analysis
# Scatter Plot
sns.scatterplot(x="total_rooms", y="median_house_value", data=df)

plt.show()

#Scatter Plot with Regression
sns.regplot(x="total_rooms", y="median_house_value", data=df)

plt.show()

#Box Plot
sns.boxplot(x="housing_median_age", y="median_house_value", data=df)

plt.show()

# Violin Plot
sns.violinplot(x="housing_median_age", y="median_house_value", data=df)

plt.show()

#Use Hue for Sub-Categories
sns.scatterplot(x="total_rooms", y="median_house_value",
                hue="housing_median_age", data=df)

plt.show()

#Identify Correlation Trend
df[["total_rooms","median_house_value"]].corr()

#Detect Outliers
sns.boxplot(x="housing_median_age", y="median_house_value", data=df)

plt.show()

#Save Visualization
sns.scatterplot(x="total_rooms", y="median_house_value", data=df)

plt.savefig("bivariate_plot.png")

plt.show()